# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [reboot13-git]
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['paypal.com/krutik013', 'link2']
